title: "Dr David Williams-Baldwin"
description: "Research Fellow"
theme: null

# Use the Minimal Mistakes theme via remote_theme:
remote_theme: mmistakes/minimal-mistakes

# Plugins required by the theme
plugins:
  - jekyll-include-cache

# Minimal Mistakes settings
minimal_mistakes_skin: "default"

# Your site settings
url: "https://drawilliamsbaldwin.github.io"
baseurl: ""

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/figures/275911576_10158192491852102_7087395702249941919_n copy.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: "/figures/275911576_10158192491852102_7087395702249941919_n copy.png"

# -- Navigation -- #

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
#  - title: "Publications"
#    url: /publications/
#  - title: "CV"
#    url: /cv/
  - title: "Contact"
    url: /contact/
